import {useState,useEffect,useRef,type ReactNode,type FormEvent} from 'react';
import {Activity,ArrowRight,BookOpen,Check,ChevronLeft,ChevronRight,ClipboardList,Clock,Database,FileCheck2,FileUp,FolderOpen,LayoutDashboard,LogOut,RefreshCw,Search,ShieldCheck,SlidersHorizontal,TriangleAlert,X} from 'lucide-react';
import {api,post,setCsrf,money,count,day,statusNames,message,ApiError,type Row} from './api';
import {captureLaunch} from './launch';

let launch=captureLaunch(window.location,window.history);
let launchPromise:Promise<Row>|undefined;
function initialSession(){
 if(!launchPromise){
  const payload=launch;launch=null;
  launchPromise=payload?(payload.error?Promise.reject(new ApiError(payload.error,422)):post('/session',payload)):api('/session');
 }
 return launchPromise;
}

type Screen='dashboard'|'cases'|'followup'|'imports'|'his'|'appeals'|'quality'|'dictionary'|'planning';
type Scope={start:string,end:string,snapshot:string};
const nav:[Screen,string,typeof Activity][]=[['dashboard','ภาพรวมการเบิกจ่าย',LayoutDashboard],['cases','แฟ้มรายเคส',FolderOpen],['followup','คิวติดตาม',ClipboardList],['appeals','อุทธรณ์',FileCheck2],['imports','นำเข้า REP / STM',FileUp],['his','ข้อมูล HIS',Database],['quality','คุณภาพข้อมูล',ShieldCheck],['dictionary','Data Dictionary',BookOpen],['planning','วางแผน',SlidersHorizontal]];
function currentFY(){const d=new Date();return d.getFullYear()+543+(d.getMonth()>=9?1:0);}
function fyScope(fy:number):Scope{return {start:`${fy-544}-10-01`,end:`${fy-543}-09-30`,snapshot:''};}
function useApi(path:string|null,refresh=0){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let alive=true;if(!path)return;setLoading(true);setError('');api(path).then(x=>{if(alive)setData(x);}).catch(e=>{if(alive){setError(message(e));setData(null);}}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[path,refresh]);
 return {data,error,loading};
}
const scoped=(scope:Scope,other:Row={})=>new URLSearchParams({start:scope.start,end:scope.end,...(scope.snapshot?{snapshot_id:scope.snapshot}:{}),...other}).toString();
function Badge({value}:{value:string}){return <span className={`badge ${value==='MATCHED'||value==='complete'||value==='resolved'?'good':value==='REP_REJECTED'||value==='failed'?'bad':'review'}`}>{statusNames[value]||value}</span>;}
function Empty({title,children}:{title:string,children?:ReactNode}){return <div className="empty"><FolderOpen size={28}/><h3>{title}</h3><p>{children}</p></div>;}
function Notice({children,tone='warning'}:{children:ReactNode,tone?:string}){return <div className={`notice ${tone}`} role={tone==='error'?'alert':undefined}><TriangleAlert size={17}/><div>{children}</div></div>;}
function Loading(){return <div className="loading" role="status"><RefreshCw size={18} className="spin"/> กำลังอ่านข้อมูล…</div>;}
function Panel({title,caption,children,action}:{title:string,caption?:string,children:ReactNode,action?:ReactNode}){return <section className="sheet"><header className="sheet-header"><div><h2>{title}</h2>{caption&&<p>{caption}</p>}</div>{action}</header>{children}</section>;}

export default function App(){
 const [session,setSession]=useState<Row|null>(null),[health,setHealth]=useState<Row|null>(null),[ready,setReady]=useState(false),[screen,setScreen]=useState<Screen>('dashboard'),[launchError,setLaunchError]=useState('');
 const [scope,setScope]=useState<Scope>(fyScope(currentFY())),[snapshots,setSnapshots]=useState<Row[]>([]),[refresh,setRefresh]=useState(0),[caseId,setCaseId]=useState<number|null>(null),[stage,setStage]=useState(''),[toast,setToast]=useState('');
 useEffect(()=>{api('/health').then(setHealth).catch(()=>{});initialSession().then(s=>{setCsrf(s.csrf);setSession(s);}).catch(e=>{if(e.code!=='BMS_SESSION_REQUIRED')setLaunchError(message(e));}).finally(()=>setReady(true));},[]);
 useEffect(()=>{if(!session)return;api('/snapshots').then(x=>{setSnapshots(x.items);if(session.mode==='demo'&&x.items[0])setScope({start:x.items[0].dstart,end:x.items[0].dend,snapshot:x.items[0].id});}).catch(e=>setToast(message(e)));},[session]);
 useEffect(()=>{if(!session)return;const timer=window.setInterval(()=>{api('/session').catch(e=>{if(e.status===401){setSession(null);setCsrf('');}});},60000);return()=>clearInterval(timer);},[session]);
 const notify=(value:string)=>{setToast(value);setRefresh(x=>x+1);};
 const openStage=(status:string)=>{setStage(status);setScreen('cases');};
 if(!ready)return <div className="login-page"><Loading/></div>;
 if(!session)return <Login demo={health?.mode==='demo'} initialError={launchError} onConnect={s=>{setCsrf(s.csrf);setSession(s);setToast('');setLaunchError('');}}/>;
 return <div className="app-shell">
  <a className="skip" href="#main">ข้ามไปเนื้อหา</a>
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><Activity size={23}/></div><div>STMREP<span>FINANCIAL FOLLOW-UP</span></div></div><div className="hospital-label">โรงพยาบาล 10929 <span className="connection-dot"/></div>
   <nav aria-label="เมนูหลัก">{nav.map(([id,label,Icon])=><button key={id} className={screen===id?'active':''} onClick={()=>{setScreen(id);setStage('');}} aria-current={screen===id?'page':undefined}><Icon size={19}/><span>{label}</span>{id==='followup'&&<span className="nav-dot"/>}</button>)}</nav>
   <div className="sidebar-foot"><p>HIS → REP → STM</p><small>ทุกยอดมีที่มา<br/>ทุกเคสมีขั้นตอนถัดไป</small><button onClick={async()=>{try{await api('/session',{method:'DELETE'});}finally{setSession(null);setCsrf('');}}}><LogOut size={17}/> ออกจาก Session</button></div>
  </aside>
  <div className="workspace"><header className="topbar"><span className="breadcrumb">ทะเบียนการเบิกจ่าย <ChevronRight size={14}/><strong>{nav.find(x=>x[0]===screen)?.[1]}</strong></span><span className="session-label"><ShieldCheck size={16}/> {session.mode==='demo'?'ข้อมูลจำลอง':'BMS Session · 10929'}<span className="small">หมดอายุ {new Date(session.expires_at*1000).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}</span></span></header>
   {session.mode==='demo'&&<div className="demo-strip">โหมดสาธิต · ทุกเคสและยอดเงินเป็นข้อมูลจำลอง ไม่มีการเชื่อม HIS หรือฐานข้อมูลจริง</div>}
   <main id="main"><div className="page-heading"><div><h1>{nav.find(x=>x[0]===screen)?.[1]}</h1><p>{screen==='dashboard'?'เห็นต้นทางของเคส ติดตามผลการเบิก และเปิดหลักฐานได้ในแฟ้มเดียว':'ตรวจต้นทางและบันทึกขั้นตอนถัดไปของแต่ละเคส'}</p></div><button className="button secondary" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={16}/> โหลดข้อมูลใหม่</button></div>
    {toast&&<div className="toast" role="status">{toast}<button className="icon-button" aria-label="ปิดข้อความ" onClick={()=>setToast('')}><X size={17}/></button></div>}
    {['dashboard','cases','followup'].includes(screen)&&<ScopeBar scope={scope} setScope={s=>{setScope(s);setRefresh(x=>x+1);}} snapshots={snapshots}/>}
    {screen==='dashboard'&&<Dashboard scope={scope} refresh={refresh} openCase={setCaseId} openStage={openStage}/>}
    {(screen==='cases'||screen==='followup')&&<Cases scope={scope} refresh={refresh} openCase={setCaseId} stage={stage} followup={screen==='followup'}/>}
    {screen==='imports'&&<Imports refresh={refresh} notify={notify} demo={session.mode==='demo'}/>}
    {screen==='his'&&<His refresh={refresh} notify={notify} snapshots={snapshots} onSnapshotRefresh={()=>api('/snapshots').then(x=>setSnapshots(x.items))} demo={session.mode==='demo'}/>}
    {screen==='appeals'&&<Appeals refresh={refresh} openCases={()=>setScreen('cases')}/>}
    {screen==='quality'&&<Quality refresh={refresh} snapshot={scope.snapshot}/>}
    {screen==='dictionary'&&<Dictionary/>}
    {screen==='planning'&&<Planning/>}
    <footer className="workspace-footer">STMREP · โรงพยาบาล 10929<span>ค่าเรียกเก็บ ≠ ต้นทุน · STM ต้องมีหลักฐานโอนก่อนเป็นเงินรับ</span></footer>
   </main>
  </div>
  {caseId!==null&&<CaseFile id={caseId} onClose={()=>setCaseId(null)} notify={notify} demo={session.mode==='demo'}/>}
 </div>;
}

function Login({demo,onConnect,initialError=''}:{demo:boolean,onConnect:(s:Row)=>void,initialError?:string}){
 const [code,setCode]=useState(''),[marketplace,setMarketplace]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(initialError);
 const connect=async(event?:FormEvent)=>{event?.preventDefault();setBusy(true);setError('');try{onConnect(await post(demo?'/session/demo':'/session',{session_code:code.trim(),marketplace_token:marketplace||undefined}));setCode('');setMarketplace('');}catch(e){setError(message(e));}finally{setBusy(false);}};
 return <div className="login-page"><div className="login-intro"><div className="login-brand"><Activity size={30}/> STMREP · 10929</div><h1>ติดตามการเบิกจ่าย<br/>จากเคสถึงหลักฐาน</h1><p>ใช้ HIS เป็นตัวตั้ง เชื่อมผล REP และ STM<br/>ให้เคสที่ต้องติดตามมีเจ้าของและขั้นตอนถัดไป</p><div className="login-rail"><span>01 HIS</span><ArrowRight size={18}/><span>02 REP</span><ArrowRight size={18}/><span>03 STM</span></div></div><section className="login-form"><span className="folder-tab">เชื่อมต่อข้อมูล</span><h2>{demo?'เปิดแฟ้มสาธิต':'เข้าใช้งานด้วย BMS Session'}</h2><p>{demo?'ทดลองหน้าจอด้วยข้อมูลจำลอง โดยไม่อ่านหรือส่งข้อมูลผู้ป่วยจริง':'Backend จะตรวจโรงพยาบาล ปลายทาง และอายุ Session ก่อนเข้าใช้งาน'}</p><form onSubmit={connect}>{!demo&&<><label>รหัส BMS Session<input value={code} onChange={e=>setCode(e.target.value)} type="password" autoComplete="off" required maxLength={512}/></label><details><summary>Marketplace token (หาก API กำหนด)</summary><label>Token<input type="password" autoComplete="off" value={marketplace} onChange={e=>setMarketplace(e.target.value)}/></label></details></>}{error&&<Notice tone="error">{error}</Notice>}<button className="button primary wide" disabled={busy}>{busy?'กำลังตรวจ Session…':demo?'เข้าสู่ข้อมูลจำลอง':'เชื่อมต่อ Session'}<ArrowRight size={17}/></button></form><small><ShieldCheck size={15}/> Session เก็บฝั่ง server และไม่บันทึกลง browser storage</small></section></div>;
}

function ScopeBar({scope,setScope,snapshots}:{scope:Scope,setScope:(s:Scope)=>void,snapshots:Row[]}){
 const startFy=Number(scope.start.slice(0,4))+543+(Number(scope.start.slice(5,7))>=10?1:0),endFy=Number(scope.end.slice(0,4))+543+(Number(scope.end.slice(5,7))>=10?1:0),fy=startFy===endFy?String(startFy):'custom';
 return <div className="scope-bar"><label>ปีงบประมาณ<select value={fy} onChange={e=>{if(e.target.value!=='custom')setScope({...fyScope(Number(e.target.value)),snapshot:scope.snapshot});}}><option value="custom">ช่วงวันที่กำหนดเอง</option>{Array.from({length:12},(_,i)=>currentFY()-i).map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>ตั้งแต่<input type="date" value={scope.start} max={scope.end} onChange={e=>setScope({...scope,start:e.target.value})}/></label><label>ถึง<input type="date" value={scope.end} min={scope.start} onChange={e=>setScope({...scope,end:e.target.value})}/></label><label className="snapshot-select">ชุดข้อมูล HIS<select value={scope.snapshot} onChange={e=>setScope({...scope,snapshot:e.target.value})}><option value="">ฉบับล่าสุดที่พร้อมใช้งาน</option>{snapshots.map(s=><option key={s.id} value={s.id}>{day(s.dstart)} – {day(s.dend)} · {s.status}</option>)}</select></label></div>;
}

function Dashboard({scope,refresh,openCase,openStage}:{scope:Scope,refresh:number,openCase:(n:number)=>void,openStage:(s:string)=>void}){
 const {data,error,loading}=useApi('/overview?'+scoped(scope),refresh);
 if(loading&&!data)return <Loading/>;if(error)return <Notice tone="error">{error}</Notice>;if(!data)return null;
 const f=data.financial||{},h=data.his||{},meta=data.meta||{};
 return <>
  {!meta.range_covered&&meta.mode!=='demo'&&<Notice>ช่วงวันที่เลือกยังไม่ครอบคลุมด้วย snapshot นี้ ยอดแสดงเฉพาะข้อมูลที่อ่านพบ ไม่ใช่ความครบถ้วนทั้งโรงพยาบาล</Notice>}
  {meta.statement_cache?.stale&&<Notice>REP / STM มีรายการใหม่รอปรับรายงาน ยอด cache เดิมยังไม่พร้อมรับรอง · {count(meta.statement_cache.dirty?.claims)} เคลมรอปรับ</Notice>}
  <div className="source-line"><span><span className="connection-dot"/> {data.his?'ตัวตั้งจาก encounter ใน HIS':'ยังไม่มี snapshot HIS'}</span><span>ข้อมูล ณ {day(meta.as_of)} · OPD วันบริการ / IPD วันจำหน่าย</span></div>
  <section className="evidence-rail" aria-label="ขั้นตอนหลักฐานการเงิน"><button onClick={()=>openStage('SUBMISSION_UNVERIFIED')}><span className="rail-index">01 / ต้นทาง</span><div><Database size={22}/><h2>HIS</h2></div><strong>{count(h.encounters)}</strong><span>ครั้งรับบริการที่จัดช่วงเวลาได้</span><small>OPD {count(h.op_visits)} · IPD {count(h.ip_admissions)}</small></button><ArrowRight className="rail-arrow"/><button onClick={()=>openStage('STM_PENDING')}><span className="rail-index">02 / ผลการส่งเบิก</span><div><FileCheck2 size={22}/><h2>REP</h2></div><strong>{money(f.rep_nhso_amount)} <em>บาท</em></strong><span>ชดเชยส่วน สปสช. ที่จับคู่ได้</span><small>{count(data.sources?.find((s:Row)=>s.source==='REP')?.files)} ไฟล์ในฐานข้อมูล</small></button><ArrowRight className="rail-arrow"/><button onClick={()=>openStage('STATEMENT_PARTIAL')}><span className="rail-index">03 / Statement</span><div><ClipboardList size={22}/><h2>STM</h2></div><strong>{money(f.stm_net_amount)} <em>บาท</em></strong><span>ยอดสุทธิตาม statement ที่จับคู่ได้</span><small>ยังไม่ใช่หลักฐานเงินโอน</small></button></section>
  <div className="dashboard-grid"><div className="dashboard-main"><Panel title="บัญชีภาพรวม" caption={`ผู้มารับบริการ ${count(h.patients)} คน · ทะเบียนทั้งหมด ${count(h.registry?.registry_hn)} HN · ยังนอน ${count(h.unallocated_dates?.active_admissions)} AN`}><dl className="money-ledger">{[['ค่าเรียกเก็บ HIS',f.his_charge_amount,'รายการรักษา / สรุป HIS ตาม coverage'],['ยอดส่งเบิกที่มีหลักฐาน',f.submitted_amount,'ใช้รอบล่าสุดของแต่ละองค์ประกอบ'],['ต้นทุนรายการที่ยืนยัน',f.observed_item_cost,`มีต้นทุน ${count(f.cost_known_count)} / ${count(f.line_count)} รายการ`],['ต้นทุนประมาณการ',f.estimated_item_cost,'ราคาปัจจุบันจากทะเบียนรายการ'],['เงินรับที่จัดสรรถึงเคส',f.cash_received_amount,'ต้องมีหลักฐานโอนและผ่านการตรวจ']].map(([label,value,hint])=><div key={label}><dt>{label}<small>{hint}</small></dt><dd>{money(value)}<span>บาท</span></dd></div>)}</dl></Panel>
   <Panel title="แนวโน้มตามเดือนบริการ" caption="เปรียบเทียบยอดบนขอบเขตข้อมูลเดียวกัน"><Trend rows={data.trend||[]}/></Panel>
  </div><aside className="work-queue"><Panel title="ขั้นตอนที่ต้องติดตาม" caption="เลือกกลุ่มเพื่อเปิดทะเบียนเคส"><div className="status-stack">{data.status_counts?.length?data.status_counts.map((s:Row)=><button key={s.tracking_status} onClick={()=>openStage(s.tracking_status)}><span className={'status-dot '+(s.tracking_status==='MATCHED'?'green':'amber')}/><span>{statusNames[s.tracking_status]||s.tracking_status}</span><strong>{count(s.count)}</strong><ChevronRight size={15}/></button>):<Empty title="รอตัวตั้ง HIS">อ่าน HIS เพื่อแสดงคิวเคสที่ต้องติดตาม</Empty>}</div><div className="queue-divider">แฟ้มที่ควรเปิดตรวจ</div>{data.worklist?.slice(0,5).map((c:Row)=><button className="queue-case" key={c.id} onClick={()=>openCase(c.id)}><span className="case-stamp">{c.care_type}</span><div><strong>HN {c.hn||'—'}</strong><small>{statusNames[c.tracking_status]} · {c.aging?.days??'—'} วันจากบริการ</small></div><ChevronRight size={16}/></button>)}</Panel><div className="scope-note"><BookOpen size={18}/><strong>ตัวหารต้องผ่านกฎสิทธิก่อน</strong><p>การพบ REP หรือ STM ยังไม่ยืนยันว่าเรียกเก็บครบทุกบริการ อัตราความครบถ้วนจะแสดงเมื่อกฎและตัวตั้งผ่านตรวจ</p></div></aside></div>
  {!data.his&&<Empty title="เริ่มด้วยข้อมูล HIS">ไปที่ “ข้อมูล HIS” เพื่ออ่าน encounter ในช่วงเวลาที่ต้องการ REP และ STM เดิมยังอยู่ในฐานข้อมูล</Empty>}
  <div className="metadata-line">Snapshot: {meta.snapshot_id||'ยังไม่มี'} · contributing: ค่าเรียกเก็บ {count(f.charge_contributing_count)} เคส / STM {count(f.stm_contributing_count)} เคส</div>
 </>;
}

function Trend({rows}:{rows:Row[]}){
 if(!rows.length)return <Empty title="ยังไม่มีข้อมูลในช่วงที่เลือก">เลือกช่วงที่ครอบคลุมด้วย snapshot</Empty>;
 const max=Math.max(...rows.map(r=>Number(r.his_charge_amount)||0),1);
 return <div className="trend"><div className="chart-legend"><span><i className="his"/>ค่าเรียกเก็บ HIS</span><span><i className="rep"/>REP ส่วน สปสช.</span><span><i className="stm"/>STM</span></div><div className="chart-bars">{rows.map(r=><div className="chart-month" key={r.month}><div className="bar-group">{[['his','his_charge_amount'],['rep','rep_nhso_amount'],['stm','stm_net_amount']].map(([cls,f])=><div className={'bar '+cls} style={{height:r[f]===null?'0':`${Math.max(2,Number(r[f])/max*100)}%`}} key={f} title={`${r.month} ${f}: ${money(r[f])} บาท`}/>)}</div><span>{r.month}</span></div>)}</div><details className="chart-data"><summary>ดูค่าตัวเลข</summary><div className="table-scroll"><table><thead><tr><th>เดือน</th><th className="num">HIS</th><th className="num">REP</th><th className="num">STM</th></tr></thead><tbody>{rows.map(r=><tr key={r.month}><td>{r.month}</td><td className="num">{money(r.his_charge_amount)}</td><td className="num">{money(r.rep_nhso_amount)}</td><td className="num">{money(r.stm_net_amount)}</td></tr>)}</tbody></table></div></details></div>;
}

function Cases({scope,refresh,openCase,stage,followup}:{scope:Scope,refresh:number,openCase:(n:number)=>void,stage:string,followup:boolean}){
 const [care,setCare]=useState(''),[status,setStatus]=useState(stage||(followup?'FOLLOWUP':'')),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[cursor,setCursor]=useState(0),[history,setHistory]=useState<number[]>([]),[orphans,setOrphans]=useState(false);
 useEffect(()=>{setStatus(stage||(followup?'FOLLOWUP':''));setCursor(0);setHistory([]);},[stage,scope]);
 const params={...(care?{care}:{}),...(status?{status}:{}),...(query?{search:query}:{}),cursor:String(cursor),limit:'50'};
 const {data,error,loading}=useApi((orphans?'/orphans?':'/cases?')+scoped(scope,params),refresh);
 const reset=()=>{setCursor(0);setHistory([]);};
 return <Panel title={orphans?'REP / STM ที่ยังไม่พบ HIS':followup?'ทะเบียนเคสสำหรับติดตาม':'ทะเบียนแฟ้มรายเคส'} caption="หนึ่งแถวต่อ encounter · โหลดครั้งละ 50 เคส"><form className="table-filters" onSubmit={e=>{e.preventDefault();setQuery(search);reset();}}><label className="search-field"><Search size={17}/><input aria-label="ค้นชื่อ HN AN VN" placeholder="ค้น HN, AN, VN หรือชื่อ" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="button secondary">ค้นหา</button><select aria-label="ประเภทบริการ" value={care} onChange={e=>{setCare(e.target.value);reset();}}><option value="">OPD และ IPD</option><option value="OP">OPD</option><option value="IP">IPD</option></select><select aria-label="สถานะเคส" value={status} onChange={e=>{setStatus(e.target.value);reset();}}><option value="">ทุกสถานะ</option><option value="FOLLOWUP">เคสต้องติดตาม / มีงานเปิด</option>{Object.entries(statusNames).filter(([k])=>k===k.toUpperCase()).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></form>
  <div className="folder-tabs"><button className={!orphans?'selected':''} onClick={()=>{setOrphans(false);reset();}}>ตัวตั้ง HIS</button><button className={orphans?'selected':''} onClick={()=>{setOrphans(true);reset();}}>REP / STM ไม่มีคู่ HIS</button></div>
  {followup&&<div className="inline-caption">อายุรายการอิงวันบริการ ใช้จัดลำดับงานทั่วไป · กำหนดส่งตามกฎยังต้องยืนยัน</div>}
  {error&&<Notice tone="error">{error}</Notice>}{loading&&<Loading/>}
  {!loading&&data?.items?.length===0&&<Empty title="ไม่พบเคสในขอบเขตนี้">ลองเปลี่ยนช่วงเวลา ตัวกรอง หรืออ่าน HIS ให้ครอบคลุม</Empty>}
  {!!data?.items?.length&&<div className="table-scroll"><table className="case-table"><thead><tr><th>แฟ้ม / ผู้รับบริการ</th><th>บริการ / สิทธิ</th>{!orphans&&<><th className="num">ค่าเรียกเก็บ HIS</th><th className="num">REP · สปสช.</th><th className="num">STM สุทธิ</th><th>ขั้นตอน / อายุ</th><th aria-label="เปิดแฟ้ม"/></>}</tr></thead><tbody>{data.items.map((c:Row)=><tr key={c.id}><td>{orphans?<><strong>{c.tran_id}</strong><small>HN {c.hn||'—'} · AN {c.an||'—'}</small></>:<button className="cell-link" onClick={()=>openCase(c.id)}><strong>HN {c.hn||'ยังไม่ทราบ'}</strong><span>{c.name||'ไม่พบทะเบียนผู้ป่วย'} · {c.an||c.vn||'—'}</span></button>}</td><td><span className="care-label">{c.care_type||c.patient_type}</span><small>{day(c.service_date)} · {c.pttype||c.payer_family||'สิทธิยังไม่ทราบ'}</small></td>{!orphans&&<><td className="num">{money(c.his_charge_amount)}</td><td className="num">{money(c.rep_nhso_amount)}</td><td className="num">{money(c.stm_net_amount)}</td><td><Badge value={c.tracking_status}/><small><Clock size={12}/> {c.aging?.days??'—'} วันจากบริการ</small><small>{c.task_teams||'ยังไม่มอบหมาย'} · {day(c.next_followup_date)}</small></td><td><button className="icon-button" aria-label={`เปิดแฟ้ม ${c.hn}`} onClick={()=>openCase(c.id)}><ChevronRight size={18}/></button></td></>}</tr>)}</tbody></table></div>}
  <div className="pagination"><span>{count(data?.count)} เคสในตัวกรอง · ไม่รวมแถววินิจฉัยหรือยาเป็นเคสเพิ่ม</span><div><button className="button secondary" disabled={!history.length||loading} onClick={()=>{setCursor(history[history.length-1]);setHistory(history.slice(0,-1));}}><ChevronLeft size={15}/> ก่อนหน้า</button><button className="button secondary" disabled={!data?.next_cursor||loading} onClick={()=>{setHistory([...history,cursor]);setCursor(data!.next_cursor);}}>ถัดไป <ChevronRight size={15}/></button></div></div>
 </Panel>;
}

function CaseFile({id,onClose,notify,demo}:{id:number,onClose:()=>void,notify:(s:string)=>void,demo:boolean}){
 const ref=useRef<HTMLDialogElement>(null),[tab,setTab]=useState('overview'),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[moreLines,setMoreLines]=useState<Row[]>([]),[lineCursor,setLineCursor]=useState<number|null>(null);
 const {data,loading,error:loadError}=useApi('/cases/'+id,version);
 useEffect(()=>{ref.current?.showModal();const d=ref.current;return()=>d?.close();},[]);
 useEffect(()=>{if(data)setLineCursor(data.lines_next_cursor);},[data]);
 const run=async(action:()=>Promise<any>,success:string)=>{setBusy(true);setError('');try{await action();notify(success);setVersion(v=>v+1);}catch(e){setError(message(e));}finally{setBusy(false);}};
 const c=data?.case||{};
 return <dialog ref={ref} className="case-dialog" aria-labelledby="case-file-heading" onCancel={onClose}><div className="file-heading"><div><span className="folder-tab">แฟ้ม {c.care_type||'เคส'} · {c.an||c.vn||id}</span><h2 id="case-file-heading">HN {c.hn||'—'}</h2><p>{c.name||'กำลังอ่านแฟ้ม'} · {day(c.service_date)} · สิทธิ {c.pttype||'—'}</p></div><button className="icon-button" aria-label="ปิดแฟ้ม" onClick={onClose}><X size={22}/></button></div>{loading&&!data?<Loading/>:loadError?<Notice tone="error">{loadError}</Notice>:data&&<>
  <div className="file-rail"><span className="reached"><Check size={16}/> HIS</span><ArrowRight size={16}/><span className={c.rep_observed_count?'reached':''}>{c.rep_observed_count?<Check size={16}/>:<Clock size={16}/>} REP</span><ArrowRight size={16}/><span className={c.statement_rows?'reached':''}>{c.statement_rows?<Check size={16}/>:<Clock size={16}/>} STM</span><Badge value={c.tracking_status}/></div>
  <div className="folder-tabs" role="tablist" aria-label="รายละเอียดแฟ้ม">{[['overview','ภาพรวม'],['lines','รายการรักษา'],['sources','หลักฐาน / Timeline'],['peers','เคสใกล้เคียง'],['action','ติดตาม / อุทธรณ์']].map(([key,label])=><button role="tab" id={`case-tab-${key}`} aria-controls="case-tab-panel" tabIndex={tab===key?0:-1} onKeyDown={event=>{const keys=["overview","lines","sources","peers","action"];const i=keys.indexOf(key);const next=event.key==="ArrowRight"?keys[(i+1)%keys.length]:event.key==="ArrowLeft"?keys[(i+keys.length-1)%keys.length]:event.key==="Home"?keys[0]:event.key==="End"?keys[keys.length-1]:null;if(next){event.preventDefault();setTab(next);document.getElementById(`case-tab-${next}`)?.focus();}}} aria-selected={tab===key} className={tab===key?'selected':''} key={key} onClick={()=>setTab(key)}>{label}</button>)}</div>
  <div className="file-content" role="tabpanel" id="case-tab-panel" aria-labelledby={`case-tab-${tab}`} tabIndex={0}>{error&&<Notice tone="error">{error}</Notice>}
   {tab==='overview'&&<><div className="case-amounts">{[['ค่าเรียกเก็บ HIS',c.his_charge_amount],['ชดเชย REP · สปสช.',c.rep_nhso_amount],['STM สุทธิ',c.stm_net_amount],['เงินรับมีหลักฐาน',c.cash_received_amount],['ต้นทุนที่ยืนยัน',c.observed_item_cost],['ต้นทุนประมาณการ',c.estimated_item_cost]].map(([label,value])=><div key={label}><span>{label}</span><strong>{money(value)} <em>บาท</em></strong></div>)}</div><Notice>ต้นทุนใช้งานได้ {count(c.cost_known_count)} / {count(c.line_count)} รายการ · ยอดส่วนต่างยังไม่ใช่กำไรสุทธิ</Notice><h3>บริบทการรักษา</h3><dl className="facts"><dt>โรคหลัก</dt><dd>{c.pdx||'ยังไม่ลง / ยังไม่พบ'}</dd><dt>DRG / Grouper</dt><dd>{c.drg||'—'} / {c.grouper_version||'—'}</dd><dt>adjRW / LOS</dt><dd>{c.adjrw||'—'} / {c.los??'—'} วัน</dd><dt>ผลจำหน่าย (รหัสต้นทาง)</dt><dd>{c.dchtype||'—'} / {c.dchstts||'—'} · รอตรวจ codebook</dd><dt>หอผู้ป่วย / แผนก</dt><dd>{c.ward||'—'} / {c.department||'—'}</dd><dt>ความสอดคล้องผู้ป่วย</dt><dd>{c.identity_status}</dd><dt>กฎที่ควรส่งเบิก</dt><dd>{data.rule?.status==='APPLICABLE'?data.rule.payment_basis:'ยังไม่มีกฎที่ยืนยันใช้กับเคสนี้'}</dd></dl><h3>ผลลัพธ์ที่สังเกตได้</h3><p className="muted">กลับ admit ภายใน 28 วัน: {data.readmission?.observed===true?'พบในโรงพยาบาลนี้':data.readmission?.observed===false?'ยังไม่พบในช่วงที่อ่านครบ':'ยังประเมินไม่ได้ / ช่วงสังเกตไม่ครบ'} · ไม่สรุปว่าเป็น unplanned readmission</p><details><summary>วินิจฉัยและหัตถการ</summary>{data.diagnoses?.map((d:Row,i:number)=><p className="muted" key={i}>{d.payload?.icd10} · ชนิด {d.payload?.diagtype}</p>)}{data.procedures?.map((d:Row,i:number)=><p className="muted" key={i}>{d.payload?.icd9||d.payload?.icd9cm}</p>)}{(data.truncation?.diagnoses||data.truncation?.procedures)&&<Notice>แสดงไม่เกิน 100 รายการต่อหมวด เปิด snapshot records ภายในระบบเพื่อดูทั้งหมด</Notice>}</details><h3>องค์ประกอบเคลม</h3>{!data.claims?.length?<p className="muted">ยังไม่พบคู่ที่ยืนยันได้ HN หรือ CID อย่างเดียวระบุครั้งรับบริการไม่ได้</p>:<div className="table-scroll"><table><thead><tr><th>TRAN_ID / REP</th><th>สิทธิ / คู่เชื่อม</th><th className="num">REP</th><th className="num">STM</th></tr></thead><tbody>{data.claims.map((q:Row)=><tr key={q.claim_id}><td>{q.tran_id}<small>{q.rep_no||'ไม่พบ REP ล่าสุด'}</small></td><td>{q.payer_family}<small>{q.link_status} · {q.method||'จำลอง'}</small></td><td className="num">{money(q.nhso_amount)}</td><td className="num">{money(q.statement_amount)}</td></tr>)}</tbody></table></div>}</>}
   {tab==='lines'&&<><h3>รายการ HIS ตามต้นทาง</h3><p className="muted">รายการที่มี AN เชื่อม IPD ก่อน · ราคาทะเบียนปัจจุบันแสดงเป็นประมาณการ</p><div className="table-scroll"><table><thead><tr><th>รหัส / รายการ</th><th className="num">จำนวน</th><th className="num">ค่าเรียกเก็บ</th><th className="num">ต้นทุนยืนยัน</th><th className="num">ประมาณการ</th></tr></thead><tbody>{[...(data.lines||[]),...moreLines].map((l:Row)=><tr key={l.id}><td>{l.item_name||l.icode}<small>{l.icode} · Billcode {l.billcode||'—'}</small></td><td className="num">{l.quantity??'—'}</td><td className="num">{money(l.charge_amount)}</td><td className="num">{money(l.observed_item_cost)}</td><td className="num">{money(l.estimated_item_cost)}<small>{l.cost_method==='unverified'?'ต้นทุน HIS ยังไม่ยืนยัน':''}</small></td></tr>)}</tbody></table></div>{data.instruments?.items?.length>0&&<><h3>เครื่องมือ HIS เทียบ REP รอบล่าสุด</h3><p className="muted">ทะเบียนเครื่องมือปี 2566 ใช้ระบุรายการเท่านั้น ยังไม่รับรองอัตรา/สิทธิ และไม่ประกาศความครบถ้วน</p><div className="table-scroll"><table><thead><tr><th>Billcode</th><th className="num">จำนวน HIS</th><th className="num">จำนวน REP</th><th className="num">ชดเชย REP</th></tr></thead><tbody>{data.instruments.items.map((r:Row)=><tr key={r.billcode}><td>{r.billcode}</td><td className="num">{r.his_quantity??'—'}</td><td className="num">{r.rep_quantity??'—'}</td><td className="num">{money(r.rep_compensation)}</td></tr>)}</tbody></table></div></>}{lineCursor&&<button className="button secondary" onClick={async()=>{try{const p=await api(`/cases/${id}/lines?cursor=${lineCursor}&limit=50`);setMoreLines([...moreLines,...p.items]);setLineCursor(p.next_cursor);}catch(e){setError(message(e));}}}>โหลด 50 รายการถัดไป</button>}</>}
   {tab==='sources'&&<><h3>เส้นทางหลักฐาน</h3>{data.truncation?.statements&&<Notice>แสดง statement ไม่เกิน 200 แถวในแฟ้มนี้ เปิดต้นฉบับหรือ source table เพื่อดูครบ</Notice>}<ol className="timeline"><li><span className="timeline-point"/><div><strong>HIS · {c.encounter_key}</strong><p>บริการ {day(c.service_date)} · อ่านพบ {day(c.as_of)}</p><small>Snapshot {c.snapshot_id}</small></div></li>{data.claims?.map((q:Row)=><li key={'q'+q.claim_id}><span className="timeline-point rep"/><div><strong>REP · {q.rep_no||'ยังไม่พบรอบล่าสุด'}</strong><p>TRAN_ID {q.tran_id} · {money(q.nhso_amount)} บาท</p><small>{q.method} · คู่ {q.link_status}</small></div></li>)}{data.statements?.map((s:Row)=><li key={'s'+s.id}><span className="timeline-point stm"/><div><strong>STM · {s.document_ref}</strong><p>{money(s.net_amount)} บาท · ชีต {s.sheet} · แถว Excel {s.source_row}</p><small>Statement row ID {s.id} · วันรายงาน {day(s.reported_at)}</small></div></li>)}{data.events?.map((e:Row)=><li key={e.id}><span className="timeline-point"/><div><strong>{e.event_type} · {e.verification}</strong><p>{day(e.occurred_at)} · {money(e.amount)} บาท</p><small>{e.source_ref}</small></div></li>)}</ol><p className="muted">วันรายงานและวันอ่านพบไม่แทนวันส่งจริง · หลักฐานรอบต้นทางเก็บครบใน archive</p></>}
   {tab==='peers'&&<><h3>เปรียบเทียบเคสใกล้เคียง</h3><p>{data.peers?.definition}</p><Notice>{data.peers?.small_sample?'กลุ่มต่ำกว่า 20 เคส ผลเปรียบเทียบยังมีตัวอย่างน้อย':'ผลเปรียบเทียบเชิงพรรณนา ยังไม่ได้ปรับความเสี่ยงทางคลินิก'} · {count(data.peers?.count)} เคส</Notice><div className="table-scroll"><table><thead><tr><th>ตัวชี้วัด</th><th className="num">เคสนี้</th><th className="num">Median</th><th className="num">P75</th><th className="num">P90</th><th>เคสมีข้อมูล</th></tr></thead><tbody>{[['his_charge_amount','ค่าเรียกเก็บ HIS'],['stm_net_amount','STM'],['observed_item_cost','ต้นทุนครบทุกบรรทัด']].map(([k,label])=><tr key={k}><td>{label}</td><td className="num">{money(c[k])}</td><td className="num">{money(data.peers?.summary?.[k]?.median)}</td><td className="num">{money(data.peers?.summary?.[k]?.p75)}</td><td className="num">{money(data.peers?.summary?.[k]?.p90)}</td><td>{count(data.peers?.summary?.[k]?.contributing_count)}</td></tr>)}</tbody></table></div></>}
   {tab==='action'&&<><TaskForm id={id} busy={busy} submit={body=>run(()=>post('/tasks',body),'บันทึกงานติดตามแล้ว')}/><h3>งานในแฟ้ม</h3>{data.tasks?.length?data.tasks.map((t:Row)=><div className="task-entry" key={t.id}><Badge value={t.status}/><strong>{t.reason}</strong><p>{t.team} · ติดตาม {day(t.due_date)} · {t.note}</p></div>):<p className="muted">ยังไม่มีงานที่บันทึกในแฟ้มนี้</p>}<EvidenceForm id={id} busy={busy} submit={body=>run(()=>post('/observations',body),'บันทึกหลักฐานแล้ว')}/><h3>เปิดอุทธรณ์</h3><p className="muted">ตรึงยอดฐานต่อเคลม ไฟล์ APPEAL เพียงอย่างเดียวยังไม่ยืนยันว่าชนะอุทธรณ์</p><AppealForm id={id} claims={data.claims||[]} busy={busy} submit={body=>run(()=>post('/appeals',body),'เปิดอุทธรณ์และตรึงฐานแล้ว')}/>{data.appeals?.map((a:Row)=><div className="task-entry" key={a.id}><strong>{a.reason}</strong><p>ฐาน {money(a.baseline_amount)} · เพิ่มสุทธิ {money(a.incremental_amount)} บาท · {a.status}</p>{a.status!=='resolved'&&!demo&&<AppealResultForm id={a.id} busy={busy} submit={body=>run(()=>post('/appeals/'+a.id+'/result',body),'บันทึกผลอุทธรณ์แล้ว')}/>}</div>)}</>}
   <div className="metadata-line">Snapshot {c.snapshot_id} · ณ {day(c.as_of)} · ย้อนต้นทางได้ทุกแถว</div>
  </div></>}</dialog>;
}

function TaskForm({id,busy,submit}:{id:number,busy:boolean,submit:(b:Row)=>void}){
 const [reason,setReason]=useState('ตรวจหลักฐานและติดตามผลเบิก'),[team,setTeam]=useState('ทีมเรียกเก็บ'),[status,setStatus]=useState('open'),[due,setDue]=useState(''),[note,setNote]=useState('');
 return <form className="action-form" onSubmit={e=>{e.preventDefault();submit({case_id:id,reason,team,status,due_date:due||null,note});}}><h3>มอบหมายขั้นตอนถัดไป</h3><label>เรื่องติดตาม<input value={reason} required maxLength={100} onChange={e=>setReason(e.target.value)}/></label><div className="form-grid"><label>ทีมรับผิดชอบ<input value={team} maxLength={100} onChange={e=>setTeam(e.target.value)}/></label><label>วันติดตามถัดไป<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><label>สถานะ<select value={status} onChange={e=>setStatus(e.target.value)}>{['open','in_progress','waiting','resolved'].map(x=><option key={x} value={x}>{statusNames[x]}</option>)}</select></label><label>หมายเหตุ<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><button className="button primary" disabled={busy}>บันทึกงานติดตาม <Check size={16}/></button></form>;
}
function EvidenceForm({id,busy,submit}:{id:number,busy:boolean,submit:(b:Row)=>void}){
 const [type,setType]=useState('SUBMISSION'),[amount,setAmount]=useState(''),[total,setTotal]=useState(''),[ref,setRef]=useState(''),[time,setTime]=useState(''),[reviewed,setReviewed]=useState(false),[component,setComponent]=useState('case_total');
 const requestId=useRef(crypto.randomUUID());
 return <details className="action-form"><summary>บันทึกหลักฐานส่ง / เงินรับ / กำหนดตามกฎ</summary><form onSubmit={e=>{e.preventDefault();submit({case_id:id,id:requestId.current,event_type:type,occurred_at:new Date(time).toISOString(),amount:amount||null,receipt_total:type==='CASH_RECEIPT'?total||null:null,source_ref:ref,component_key:component,verification:reviewed?'reviewed':'unverified'});}}><label>ประเภท<select value={type} onChange={e=>setType(e.target.value)}>{[['SUBMISSION','ส่งเบิกจริง'],['CASH_RECEIPT','เงินรับจริง'],['APPEAL_SENT','ส่งอุทธรณ์จริง'],['DEADLINE','กำหนดส่งที่ยืนยันแล้ว']].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div className="form-grid"><label>วันและเวลาตามหลักฐาน<input type="datetime-local" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>ยอดถึงเคสนี้ (บาท)<input inputMode="decimal" value={amount} required={type==='CASH_RECEIPT'} onChange={e=>setAmount(e.target.value)}/></label></div>{type==='CASH_RECEIPT'&&<label>ยอดรวมใบรับ / เงินโอน (บาท)<input inputMode="decimal" value={total} required onChange={e=>setTotal(e.target.value)}/></label>}<label>เลขที่ / ที่อ้างอิงหลักฐาน<input required minLength={3} value={ref} maxLength={500} onChange={e=>setRef(e.target.value)}/></label>{type==='SUBMISSION'&&<label>องค์ประกอบการส่ง (ใช้คีย์เดิมเมื่อส่งแก้ไข)<input required value={component} onChange={e=>setComponent(e.target.value)}/></label>}<label className="checkbox-label"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>ตรวจหลักฐานและความหมายยอดแล้ว</label><p className="muted">ใช้ UUID เดิมเมื่อ retry หลักฐานเดิม · เปลี่ยนเป็นรายการใหม่ด้วยการเปิดแฟ้มใหม่</p><button className="button secondary" disabled={busy}>บันทึกหลักฐาน</button></form></details>;
}
function AppealForm({id,claims,busy,submit}:{id:number,claims:Row[],busy:boolean,submit:(b:Row)=>void}){
 const options=claims.filter(c=>c.link_status==='linked'),[claim,setClaim]=useState(''),[reason,setReason]=useState('');const requestId=useRef(crypto.randomUUID());
 if(!options.length)return <p className="muted">ต้องมีเคลมที่จับคู่ชัดเจนก่อนเปิดอุทธรณ์</p>;
 return <form className="action-form" onSubmit={e=>{e.preventDefault();submit({case_id:id,claim_id:Number(claim||options[0].claim_id),reason,id:requestId.current});}}><label>เคลม<select value={claim||options[0].claim_id} onChange={e=>setClaim(e.target.value)}>{options.map(c=><option key={c.claim_id} value={c.claim_id}>{c.tran_id} · {c.payer_family}</option>)}</select></label><label>เหตุผล<textarea required minLength={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button secondary" disabled={busy}>เปิดอุทธรณ์พร้อมยอดฐาน</button></form>;
}
function AppealResultForm({id,busy,submit}:{id:string,busy:boolean,submit:(b:Row)=>void}){
 const [rows,setRows]=useState(''),[effect,setEffect]=useState('DELTA'),[outcome,setOutcome]=useState('approved'),[ref,setRef]=useState('');
 return <details className="action-form"><summary>ระบุผลพิจารณาจากหลักฐานใหม่</summary><form onSubmit={e=>{e.preventDefault();submit({statement_row_ids:rows.split(',').map(x=>Number(x.trim())),effect_type:effect,outcome,source_ref:ref});}}><label>Statement row IDs (คั่นด้วย comma)<input required pattern="[0-9, ]+" value={rows} onChange={e=>setRows(e.target.value)}/></label><label>ความหมายยอด<select value={effect} onChange={e=>setEffect(e.target.value)}><option value="DELTA">ยอดเพิ่ม / ลดโดยตรง</option><option value="REPLACEMENT">ยอดใหม่แทนฐานเดิม</option></select></label><label>ผล<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="approved">อนุมัติ</option><option value="partial">อนุมัติบางส่วน</option><option value="rejected">ไม่อนุมัติ</option></select></label><label>หลักฐานผล<input required minLength={3} value={ref} onChange={e=>setRef(e.target.value)}/></label><button className="button secondary" disabled={busy}>บันทึกผล · {id.slice(0,8)}</button></form></details>;
}

function Imports({refresh,notify,demo}:{refresh:number,notify:(s:string)=>void,demo:boolean}){
 const [files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[job,setJob]=useState<string|null>(null),[poll,setPoll]=useState(0);const requestId=useRef(crypto.randomUUID());
 const jobs=useApi('/jobs',refresh+poll),detail=useApi(job?'/jobs/'+job:null,refresh+poll);
 useEffect(()=>{const active=jobs.data?.items?.some((j:Row)=>['queued','inspecting','importing','syncing','refreshing','verifying'].includes(j.status));if(!active)return;const t=setInterval(()=>setPoll(v=>v+1),10000);return()=>clearInterval(t);},[jobs.data]);
 const upload=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');const body=new FormData();files.forEach(f=>body.append('files',f));try{const result=await api('/imports/uploads',{method:'POST',body,headers:{'Idempotency-Key':requestId.current}});setJob(result.job_id);notify('รับไฟล์เข้าคิวตรวจแล้ว');requestId.current=crypto.randomUUID();setFiles([]);}catch(e){setError(message(e));}finally{setBusy(false);}};
 const action=async(id:string,verb:string)=>{try{await post(`/jobs/${id}/${verb}`);notify(verb==='start'?'เริ่มนำเข้าไฟล์ที่ผ่านตรวจ':'บันทึกคำสั่งงานแล้ว');setPoll(v=>v+1);}catch(e){setError(message(e));}};
 return <><Panel title="นำเข้าไฟล์ REP และ STM" caption="ตรวจรูปแบบและยอดก่อนนำเข้า · เก็บไฟล์ต้นฉบับและทุกฉบับแก้ไข"><form className="upload-zone" onSubmit={upload}><FileUp size={30}/><h3>เลือกไฟล์ .xls จากเครื่อง</h3><p>STM_10929_*.xls หรือ eclaim_10929_*.xls<br/>ไม่เกิน 20 ไฟล์ต่อครั้ง · 100 MiB ต่อไฟล์ · 300 MiB รวม</p><label className="file-picker">ไฟล์ที่ต้องการตรวจ<input type="file" accept=".xls" multiple disabled={demo||busy} onChange={e=>{setFiles(Array.from(e.target.files||[]));requestId.current=crypto.randomUUID();}}/></label>{files.length>0&&<ul className="selected-files">{files.map(f=><li key={f.name}>{f.name}<span>{(f.size/1024/1024).toFixed(2)} MiB</span></li>)}</ul>}<button className="button primary" disabled={demo||busy||!files.length}>{busy?'กำลังรับไฟล์…':'อัปโหลดและตรวจไฟล์'}<ArrowRight size={16}/></button>{demo&&<p className="muted">โหมดจำลองไม่รับไฟล์ผู้ป่วยจริง</p>}</form></Panel>{error&&<Notice tone="error">{error}</Notice>}
 <Panel title="ประวัติงานและ checkpoint" caption="เมื่อ timeout ใช้ resume ของงานเดิม เพื่อรักษา batch UUID"><div className="job-list">{jobs.loading?<Loading/>:jobs.error?<Notice tone="error">{jobs.error}</Notice>:!jobs.data?.items?.length?<Empty title="ยังไม่มีงาน">งานอัปโหลดและ HIS sync จะแสดงที่นี่</Empty>:jobs.data.items.map((j:Row)=><div className="job" key={j.id}><button className="job-title" onClick={()=>setJob(j.id)}><strong>{j.kind==='IMPORT'?'นำเข้า REP / STM':'อ่าน HIS'} · {j.id.slice(0,8)}</strong><small>{day(j.created_at)} · {count(j.progress?.records??j.progress?.inserted)} records</small></button><Badge value={j.status}/><div className="job-actions">{j.status==='awaiting_import'&&<button className="button primary" onClick={()=>action(j.id,'start')}>นำเข้าที่ผ่านตรวจ</button>}{['paused','failed','waiting_session'].includes(j.status)&&<button className="button secondary" onClick={()=>action(j.id,'resume')}>ทำต่อ</button>}{['queued','importing','syncing','inspecting'].includes(j.status)&&<button className="button secondary" onClick={()=>action(j.id,'pause')}>พักงาน</button>}</div>{j.error_code&&<small className="error-code">{j.error_code}</small>}</div>)}</div></Panel>
 {job&&<Panel title={'รายละเอียดงาน '+job.slice(0,8)} action={<button className="icon-button" aria-label="ปิดรายละเอียดงาน" onClick={()=>setJob(null)}><X size={18}/></button>}>{detail.loading?<Loading/>:detail.error?<Notice tone="error">{detail.error}</Notice>:<><pre className="operational-json">{JSON.stringify({progress:detail.data?.progress,result:detail.data?.result,error:detail.data?.error_code},null,2)}</pre>{detail.data?.files?.map((f:Row)=><details className="file-profile" key={f.id}><summary>{f.filename} · {statusNames[f.status]||f.status}</summary><p>SHA-256: <code>{f.sha256}</code></p><pre className="operational-json">{JSON.stringify(f.profile,null,2)}</pre></details>)}</>}</Panel>}</>;
}

function His({refresh,notify,snapshots,onSnapshotRefresh,demo}:{refresh:number,notify:(s:string)=>void,snapshots:Row[],onSnapshotRefresh:()=>void,demo:boolean}){
 const [scope,setScope]=useState(fyScope(currentFY())),[busy,setBusy]=useState(false),[error,setError]=useState(''),[poll,setPoll]=useState(0);const requestId=useRef(crypto.randomUUID());const readiness=useApi('/readiness',refresh+poll),jobs=useApi('/jobs',refresh+poll);
 useEffect(()=>{if(!jobs.data?.items?.some((j:Row)=>j.kind==='HIS_SYNC'&&['queued','syncing'].includes(j.status)))return;const t=setInterval(()=>{setPoll(v=>v+1);onSnapshotRefresh();},10000);return()=>clearInterval(t);},[jobs.data]);
 const sync=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const x=await post('/his/sync',{start:scope.start,end:scope.end,request_id:requestId.current});notify('เริ่มอ่าน HIS · '+x.job_id.slice(0,8));requestId.current=crypto.randomUUID();setPoll(v=>v+1);}catch(e){setError(message(e));}finally{setBusy(false);}};
 return <><Panel title="อ่าน HIS ผ่าน BMS Session" caption="อ่านเฉพาะ query registry · ไม่รับ SQL จาก browser"><form className="sync-form" onSubmit={sync}><div className="form-grid"><label>วันเริ่ม<input type="date" value={scope.start} max={scope.end} onChange={e=>setScope({...scope,start:e.target.value})}/></label><label>วันสิ้นสุด<input type="date" value={scope.end} min={scope.start} onChange={e=>setScope({...scope,end:e.target.value})}/></label></div><p>OPD ใช้วันบริการ · IPD ใช้วันจำหน่าย และเก็บผู้ป่วยที่ยังนอนแยกไว้ ไม่ลดตัวตั้งเมื่อยังไม่มีวินิจฉัย</p><button className="button primary" disabled={demo||busy}>เริ่มอ่านและสร้าง snapshot <ArrowRight size={16}/></button></form>{error&&<Notice tone="error">{error}</Notice>}<Notice>Session หมดอายุจะพักงานรอเชื่อมใหม่ ชุดข้อมูลที่อ่านไม่ครบระบุเป็น partial / unavailable และไม่แปลงยอดที่ขาดเป็นศูนย์</Notice></Panel><Panel title="สถานะแหล่งข้อมูล"><pre className="operational-json">{JSON.stringify(readiness.data,null,2)}</pre></Panel><Panel title="Snapshot และขอบเขตที่อ่านได้"><div className="snapshot-list">{snapshots.length?snapshots.map(s=><details key={s.id}><summary>{day(s.dstart)} – {day(s.dend)} <Badge value={s.status}/></summary><p>{s.id} · ณ {day(s.completed_at)}</p><pre className="operational-json">{JSON.stringify({coverage:s.coverage,registry:s.registry_profile,cost:s.cost_semantics},null,2)}</pre></details>):<Empty title="ยังไม่มี snapshot">เริ่มจากช่วงสั้นเพื่อตรวจสิทธิ API และต้นทุน ก่อนขยายช่วงย้อนหลัง</Empty>}</div></Panel></>;
}

function Appeals({refresh,openCases}:{refresh:number,openCases:()=>void}){
 const {data,error,loading}=useApi('/appeals',refresh);
 return <Panel title="ประวัติอุทธรณ์และผลเพิ่มสุทธิ" caption="แยกจากการแก้ reject แล้วส่งใหม่" action={<button className="button secondary" onClick={openCases}>เปิดจากแฟ้มเคส <ArrowRight size={16}/></button>}>{error?<Notice tone="error">{error}</Notice>:loading?<Loading/>:!data?.items?.length?<Empty title="ยังไม่มีอุทธรณ์ที่บันทึก">เปิดแฟ้มเคส เลือกเคลม และตรึงฐานก่อนอุทธรณ์</Empty>:<div className="table-scroll"><table><thead><tr><th>แฟ้ม / เหตุผล</th><th>สถานะ</th><th className="num">ฐานเดิม</th><th className="num">เพิ่ม / ลดสุทธิ</th><th>หลักฐานผล</th></tr></thead><tbody>{data.items.map((a:Row)=><tr key={a.id}><td>{a.encounter_key}<small>{a.reason}</small></td><td>{a.status} · {a.outcome||'รอผล'}</td><td className="num">{money(a.baseline_amount)}</td><td className="num">{money(a.incremental_amount)}</td><td>{a.source_ref||'—'}</td></tr>)}</tbody></table></div>}</Panel>;
}
function Quality({refresh,snapshot}:{refresh:number,snapshot:string}){
 const {data,error,loading}=useApi('/quality'+(snapshot?'?snapshot_id='+snapshot:''),refresh);
 return <><Notice>คอลัมน์ที่มีอยู่ใน schema ยังไม่ยืนยันว่ามีข้อมูลจริง ความหมายต้นทุน วันส่ง และ deadline ต้องผ่านการตรวจต้นทาง</Notice><Panel title="รายการตรวจ HIS"><IssueTable rows={data?.his||[]} loading={loading} error={error}/></Panel><Panel title="ข้อสังเกต REP / STM" caption="ปัญหา mapping ที่เป็น error พักเอกสารก่อนรวมยอด"><IssueTable rows={data?.rep_stm||[]} loading={loading}/></Panel></>;
}
function IssueTable({rows,loading,error}:{rows:Row[],loading:boolean,error?:string}){return error?<Notice tone="error">{error}</Notice>:loading?<Loading/>:!rows.length?<Empty title="ไม่มีปัญหาที่บันทึกในขอบเขตนี้">ยังต้องตรวจ coverage และความพร้อมของแต่ละแหล่ง</Empty>:<div className="table-scroll"><table><thead><tr><th>ระดับ</th><th>ประเด็น</th><th>ชุดข้อมูล / จำนวน</th><th>หลักฐาน</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><span className={'badge '+(r.severity==='error'?'bad':'review')}>{r.severity}</span></td><td>{r.code}</td><td>{r.dataset||count(r.count)}</td><td>{r.source_key||'—'}{r.detail&&<details><summary>รายละเอียด</summary><pre className="operational-json">{JSON.stringify(r.detail,null,2)}</pre></details>}</td></tr>)}</tbody></table></div>;}
function Dictionary(){
 const {data,error,loading}=useApi('/dictionary'),[search,setSearch]=useState('');
 const tables=(data?.tables||[]).filter((t:Row)=>[t.name,t.meaning,...t.fields.map((f:Row)=>[f.name,f.meaning,f.source].join(' '))].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <Panel title="พจนานุกรมข้อมูลและที่มา" caption="คีย์จาก metadata แยกจากความสัมพันธ์ที่ยังต้องตรวจข้อมูลจริง"><label className="search-field dictionary-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นตาราง คอลัมน์ หรือความหมาย" aria-label="ค้น Data Dictionary"/></label>{loading?<Loading/>:error?<Notice tone="error">{error}</Notice>:tables.map((t:Row)=><details className="dictionary-table" key={t.name}><summary><code>{t.name}</code><span>{t.meaning}</span><small>{t.fields.length} ฟิลด์</small></summary><p>{t.grain} · {t.verification}</p><div className="table-scroll"><table><thead><tr><th>ฟิลด์ / ชนิด</th><th>ความหมาย / ที่มา</th><th>NULL / คีย์</th><th>ความเชื่อถือ / หน่วย</th></tr></thead><tbody>{t.fields.map((f:Row)=><tr key={f.name}><td><code>{f.name}</code><small>{f.type}</small></td><td>{f.meaning}<small>{f.source}</small></td><td>{f.nullable?'NULL ได้':'NOT NULL'} {f.key||''}</td><td>{f.verification}<small>{f.unit||'—'}</small></td></tr>)}</tbody></table></div></details>)}</Panel>;
}
function Planning(){
 const [volume,setVolume]=useState('100'),[charge,setCharge]=useState(''),[cost,setCost]=useState(''),[recovery,setRecovery]=useState(''),[result,setResult]=useState<Row|null>(null),[error,setError]=useState('');const forecast=useApi('/planning/forecast');
 return <><Panel title="จำลองแผนบริการและการติดตาม" caption="เปลี่ยนสมมติฐานเพื่อดูผล · เป็นสถานการณ์ ไม่ใช่คำพยากรณ์"><form className="planning-form" onSubmit={async e=>{e.preventDefault();setError('');try{setResult(await post('/planning/scenario',{volume,charge_per_case:charge||null,cost_per_case:cost||null,verified_recovery_per_case:recovery||null}));}catch(e){setError(message(e));}}}><div className="form-grid"><label>จำนวนเคส<input type="number" min="0" step="1" required value={volume} onChange={e=>setVolume(e.target.value)}/></label><label>ค่าเรียกเก็บต่อเคส (บาท)<input inputMode="decimal" value={charge} onChange={e=>setCharge(e.target.value)}/></label><label>ต้นทุนรายการต่อเคส (บาท)<input inputMode="decimal" value={cost} onChange={e=>setCost(e.target.value)}/></label><label>โอกาสเรียกเก็บเพิ่มที่มีหลักฐานต่อเคส (บาท)<input inputMode="decimal" value={recovery} onChange={e=>setRecovery(e.target.value)}/></label></div><button className="button primary">คำนวณสถานการณ์ <ArrowRight size={16}/></button></form>{error&&<Notice tone="error">{error}</Notice>}{result&&<dl className="money-ledger">{[['ค่าเรียกเก็บตามสมมติฐาน',result.charge_amount],['ต้นทุนรายการตามสมมติฐาน',result.item_cost_amount],['โอกาสเรียกเก็บเพิ่ม',result.potential_recovery]].map(([label,v])=><div key={label}><dt>{label}</dt><dd>{money(v)} <span>บาท</span></dd></div>)}</dl>}</Panel><Panel title="การพยากรณ์จากประวัติ"><Notice>{forecast.data?.status==='NOT_READY'?'ยังไม่พร้อมพยากรณ์ ต้องมีประวัติครบอย่างน้อย 24 เดือนต่อเนื่องและนิยามตัวชี้วัดผ่านตรวจ':'แบบจำลองพื้นฐานที่ผ่าน backtest'}</Notice><p className="inline-caption">ประเมินย้อนหลังตามเวลา เทียบ seasonal naive และเดือนล่าสุด พร้อมรายงาน MAE และขอบเขตข้อมูลขาด</p></Panel></>;
}
