import {useState,useEffect,useRef,type FormEvent} from 'react';
import {Activity,ArrowRight,BookOpen,Check,ChevronLeft,ChevronRight,ClipboardList,Clock,Database,FileCheck2,FileUp,FolderOpen,LayoutDashboard,LogOut,RefreshCw,Search,ShieldCheck,SlidersHorizontal,TriangleAlert,X} from 'lucide-react';
import {api,post,money,count,day,statusNames,message,type Row} from './api';
import {useApi,useVisiblePolling,currentFY,fyScope,scoped,Badge,Empty,Notice,Loading,Panel,type Scope} from './shared';
export default function CaseFile({id,onClose,notify,demo}:{id:number,onClose:()=>void,notify:(s:string)=>void,demo:boolean}){
 const ref=useRef<HTMLDialogElement>(null),[tab,setTab]=useState('overview'),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[moreLines,setMoreLines]=useState<Row[]>([]),[lineCursor,setLineCursor]=useState<number|null>(null);
 const {data,loading,error:loadError}=useApi('/cases/'+id,version);
 useEffect(()=>{ref.current?.showModal();const d=ref.current;return()=>d?.close();},[]);
 useEffect(()=>{if(data)setLineCursor(data.lines_next_cursor);},[data]);
 const run=async(action:()=>Promise<any>,success:string)=>{setBusy(true);setError('');try{await action();notify(success);setVersion(v=>v+1);}catch(e){setError(message(e));}finally{setBusy(false);}};
 const c=data?.case||{};
 return <dialog ref={ref} className="case-dialog" aria-labelledby="case-file-heading" onCancel={onClose}><div className="file-heading"><div><span className="folder-tab">แฟ้ม {c.care_type||'เคส'} · {c.an||c.vn||id}</span><h2 id="case-file-heading">HN {c.hn||'—'}</h2><p>{c.name||'กำลังอ่านแฟ้ม'} · {day(c.service_date)} · สิทธิ {c.pttype||'—'}</p></div><button className="icon-button" aria-label="ปิดแฟ้ม" onClick={onClose}><X size={22}/></button></div>{loading&&!data?<Loading/>:loadError?<Notice tone="error">{loadError}</Notice>:data&&<>
  <div className="file-rail"><span className="reached"><Check size={16}/> HIS</span><ArrowRight size={16}/><span className={c.rep_observed_count?'reached':''}>{c.rep_observed_count?<Check size={16}/>:<Clock size={16}/>} REP</span><ArrowRight size={16}/><span className={c.statement_rows?'reached':''}>{c.statement_rows?<Check size={16}/>:<Clock size={16}/>} STM</span><Badge value={c.tracking_status}/></div>
  <div className="folder-tabs" role="tablist" aria-label="รายละเอียดแฟ้ม">{[['overview','ภาพรวม'],['lines','รายการรักษา'],['sources','หลักฐาน / Timeline'],['peers','เคสใกล้เคียง'],['action','ติดตาม / อุทธรณ์']].map(([key,label])=><button role="tab" id={`case-tab-${key}`} aria-controls="case-tab-panel" tabIndex={tab===key?0:-1} onKeyDown={event=>{const keys=["overview","lines","sources","peers","action"];const i=keys.indexOf(key);const next=event.key==="ArrowRight"?keys[(i+1)%keys.length]:event.key==="ArrowLeft"?keys[(i+keys.length-1)%keys.length]:event.key==="Home"?keys[0]:event.key==="End"?keys[keys.length-1]:null;if(next){event.preventDefault();setTab(next);document.getElementById(`case-tab-${next}`)?.focus();}}} aria-selected={tab===key} className={tab===key?'selected':''} key={key} onClick={()=>setTab(key)}>{label}</button>)}</div>
  <div className="file-content" role="tabpanel" id="case-tab-panel" aria-labelledby={`case-tab-${tab}`} tabIndex={0}>{error&&<Notice tone="error">{error}</Notice>}
   {tab==='overview'&&<><div className="case-amounts">{[['ค่าเรียกเก็บ HIS',c.his_charge_amount],['ชดเชย REP · สปสช.',c.rep_nhso_amount],['STM สุทธิ',c.stm_net_amount],['เงินรับมีหลักฐาน',c.cash_received_amount],['ต้นทุนที่ยืนยัน',c.observed_item_cost],['ต้นทุนประมาณการ',c.estimated_item_cost]].map(([label,value])=><div key={label}><span>{label}</span><strong>{money(value)} <em>บาท</em></strong></div>)}</div><Notice>ต้นทุนใช้งานได้ {count(c.cost_known_count)} / {count(c.line_count)} รายการ · ยอดส่วนต่างยังไม่ใช่กำไรสุทธิ</Notice><h3>บริบทการรักษา</h3><dl className="facts"><dt>โรคหลัก</dt><dd>{c.pdx||'ยังไม่ลง / ยังไม่พบ'}</dd><dt>DRG / Grouper</dt><dd>{c.drg||'—'} / {c.grouper_version||'—'}</dd><dt>adjRW / LOS</dt><dd>{c.adjrw||'—'} / {c.los??'—'} วัน</dd><dt>ผลจำหน่าย (รหัสต้นทาง)</dt><dd>{c.dchtype||'—'} / {c.dchstts||'—'} · รอตรวจ codebook</dd><dt>หอผู้ป่วย / แผนก</dt><dd>{c.ward||'—'} / {c.department||'—'}</dd><dt>ความสอดคล้องผู้ป่วย</dt><dd>{c.identity_status}</dd><dt>กฎที่ควรส่งเบิก</dt><dd>{data.rule?.status==='APPLICABLE'?data.rule.payment_basis:'ยังไม่มีกฎที่ยืนยันใช้กับเคสนี้'}</dd></dl><h3>ผลลัพธ์ที่สังเกตได้</h3><p className="muted">กลับ admit ภายใน 28 วัน: {data.readmission?.observed===true?'พบในโรงพยาบาลนี้':data.readmission?.observed===false?'ยังไม่พบในช่วงที่อ่านครบ':'ยังประเมินไม่ได้ / ช่วงสังเกตไม่ครบ'} · ไม่สรุปว่าเป็น unplanned readmission</p><details><summary>วินิจฉัยและหัตถการ</summary>{data.diagnoses?.map((d:Row,i:number)=><p className="muted" key={i}>{d.payload?.icd10} · ชนิด {d.payload?.diagtype}</p>)}{data.procedures?.map((d:Row,i:number)=><p className="muted" key={i}>{d.payload?.icd9||d.payload?.icd9cm}</p>)}{(data.truncation?.diagnoses||data.truncation?.procedures)&&<Notice>แสดงไม่เกิน 100 รายการต่อหมวด เปิด snapshot records ภายในระบบเพื่อดูทั้งหมด</Notice>}</details><h3>องค์ประกอบเคลม</h3>{!data.claims?.length?<p className="muted">ยังไม่พบคู่ที่ยืนยันได้ HN หรือ CID อย่างเดียวระบุครั้งรับบริการไม่ได้</p>:<div className="table-scroll"><table><thead><tr><th>TRAN_ID / REP</th><th>สิทธิ / คู่เชื่อม</th><th className="num">REP</th><th className="num">STM</th></tr></thead><tbody>{data.claims.map((q:Row)=><tr key={q.claim_id}><td>{q.tran_id}<small>{q.rep_no||'ไม่พบ REP ล่าสุด'}</small></td><td>{q.payer_family}<small>{q.link_status} · {q.method||'จำลอง'}</small></td><td className="num">{money(q.nhso_amount)}</td><td className="num">{money(q.statement_amount)}</td></tr>)}</tbody></table></div>}</>}
   {tab==='lines'&&<><h3>รายการ HIS ตามต้นทาง</h3><p className="muted">รายการที่มี AN เชื่อม IPD ก่อน · ราคาทะเบียนปัจจุบันแสดงเป็นประมาณการ</p><div className="table-scroll"><table><thead><tr><th>รหัส / รายการ</th><th className="num">จำนวน</th><th className="num">ค่าเรียกเก็บ</th><th className="num">ต้นทุนยืนยัน</th><th className="num">ประมาณการ</th></tr></thead><tbody>{[...(data.lines||[]),...moreLines].map((l:Row)=><tr key={l.id}><td>{l.item_name||l.icode}<small>{l.icode} · Billcode {l.billcode||'—'}</small></td><td className="num">{l.quantity??'—'}</td><td className="num">{money(l.charge_amount)}</td><td className="num">{money(l.observed_item_cost)}</td><td className="num">{money(l.estimated_item_cost)}<small>{l.cost_method==='unverified'?'ต้นทุน HIS ยังไม่ยืนยัน':''}</small></td></tr>)}</tbody></table></div>{data.instruments?.items?.length>0&&<><h3>เครื่องมือ HIS เทียบ REP รอบล่าสุด</h3><p className="muted">ทะเบียนเครื่องมือปี 2566 ใช้ระบุรายการเท่านั้น ยังไม่รับรองอัตรา/สิทธิ และไม่ประกาศความครบถ้วน</p><div className="table-scroll"><table><thead><tr><th>Billcode</th><th className="num">จำนวน HIS</th><th className="num">จำนวน REP</th><th className="num">ชดเชย REP</th></tr></thead><tbody>{data.instruments.items.map((r:Row)=><tr key={r.billcode}><td>{r.billcode}</td><td className="num">{r.his_quantity??'—'}</td><td className="num">{r.rep_quantity??'—'}</td><td className="num">{money(r.rep_compensation)}</td></tr>)}</tbody></table></div></>}{lineCursor&&<button className="button secondary" onClick={async()=>{try{const p=await api(`/cases/${id}/lines?cursor=${lineCursor}&limit=50`);setMoreLines([...moreLines,...p.items]);setLineCursor(p.next_cursor);}catch(e){setError(message(e));}}}>โหลด 50 รายการถัดไป</button>}</>}
   {tab==='sources'&&<><h3>เส้นทางหลักฐาน</h3>{data.truncation?.statements&&<Notice>แสดง statement ไม่เกิน 200 แถวในแฟ้มนี้ เปิดต้นฉบับหรือ source table เพื่อดูครบ</Notice>}<ol className="timeline"><li><span className="timeline-point"/><div><strong>HIS · {c.encounter_key}</strong><p>บริการ {day(c.service_date)} · อ่านพบ {day(c.as_of)}</p><small>Snapshot {c.snapshot_id}</small></div></li>{data.claims?.map((q:Row)=><li key={'q'+q.claim_id}><span className="timeline-point rep"/><div><strong>REP · {q.rep_no||'ยังไม่พบรอบล่าสุด'}</strong><p>TRAN_ID {q.tran_id} · {money(q.nhso_amount)} บาท</p><small>{q.method} · คู่ {q.link_status}</small></div></li>)}{data.statements?.map((s:Row)=><li key={'s'+s.id}><span className="timeline-point stm"/><div><strong>STM · {s.document_ref}</strong><p>{money(s.net_amount)} บาท · ชีต {s.sheet} · แถว Excel {s.source_row}</p><small>Statement row ID {s.id} · วันรายงาน {day(s.reported_at)}</small></div></li>)}{data.events?.map((e:Row)=><li key={e.id}><span className="timeline-point"/><div><strong>{e.event_type} · {e.verification}</strong><p>{day(e.occurred_at)} · {money(e.amount)} บาท</p><small>{e.source_ref}</small></div></li>)}</ol><p className="muted">วันรายงานและวันอ่านพบไม่แทนวันส่งจริง · หลักฐานรอบต้นทางเก็บครบใน archive</p></>}
   {tab==='peers'&&<><h3>เปรียบเทียบเคสใกล้เคียง</h3><p>{data.peers?.definition}</p><Notice>{data.peers?.small_sample?'กลุ่มต่ำกว่า 20 เคส ผลเปรียบเทียบยังมีตัวอย่างน้อย':'ผลเปรียบเทียบเชิงพรรณนา ยังไม่ได้ปรับความเสี่ยงทางคลินิก'} · {count(data.peers?.count)} เคส</Notice><div className="table-scroll"><table><thead><tr><th>ตัวชี้วัด</th><th className="num">เคสนี้</th><th className="num">Median</th><th className="num">P75</th><th className="num">P90</th><th>เคสมีข้อมูล</th></tr></thead><tbody>{[['his_charge_amount','ค่าเรียกเก็บ HIS'],['stm_net_amount','STM'],['observed_item_cost','ต้นทุนครบทุกบรรทัด']].map(([k,label])=><tr key={k}><td>{label}</td><td className="num">{money(c[k])}</td><td className="num">{money(data.peers?.summary?.[k]?.median)}</td><td className="num">{money(data.peers?.summary?.[k]?.p75)}</td><td className="num">{money(data.peers?.summary?.[k]?.p90)}</td><td>{count(data.peers?.summary?.[k]?.contributing_count)}</td></tr>)}</tbody></table></div></>}
   {tab==='action'&&<><TaskForm id={id} busy={busy} submit={body=>run(()=>post('/tasks',body),'บันทึกงานติดตามแล้ว')}/><h3>งานในแฟ้ม</h3>{data.tasks?.length?data.tasks.map((t:Row)=><div className="task-entry" key={t.id}><Badge value={t.status}/><strong>{t.reason}</strong><p>{t.team} · ติดตาม {day(t.due_date)} · {t.note}</p></div>):<p className="muted">ยังไม่มีงานที่บันทึกในแฟ้มนี้</p>}<EvidenceForm id={id} busy={busy} submit={body=>run(()=>post('/observations',body),'บันทึกหลักฐานแล้ว')}/><h3>เปิดอุทธรณ์</h3><p className="muted">ตรึงยอดฐานต่อเคลม ไฟล์ APPEAL เพียงอย่างเดียวยังไม่ยืนยันว่าชนะอุทธรณ์</p><AppealForm id={id} claims={data.claims||[]} busy={busy} submit={body=>run(()=>post('/appeals',body),'เปิดอุทธรณ์และตรึงฐานแล้ว')}/>{data.appeals?.map((a:Row)=><div className="task-entry" key={a.id}><strong>{a.reason}</strong><p>ฐาน {money(a.baseline_amount)} · เพิ่มสุทธิ {money(a.incremental_amount)} บาท · {a.status}</p>{a.status!=='resolved'&&!demo&&<AppealResultForm id={a.id} busy={busy} submit={body=>run(()=>post('/appeals/'+a.id+'/result',body),'บันทึกผลอุทธรณ์แล้ว')}/>}</div>)}</>}
   <div className="metadata-line">Snapshot {c.snapshot_id} · ณ {day(c.as_of)} · ย้อนต้นทางได้ทุกแถว</div>
  </div></>}</dialog>;
}

function TaskForm({id,busy,submit}:{id:number,busy:boolean,submit:(b:Row)=>void}){
 const [reason,setReason]=useState('ตรวจหลักฐานและติดตามผลเบิก'),[team,setTeam]=useState('ทีมเรียกเก็บ'),[status,setStatus]=useState('open'),[due,setDue]=useState(''),[note,setNote]=useState('');
 return <form className="action-form" onSubmit={e=>{e.preventDefault();submit({case_id:id,reason,team,status,due_date:due||null,note});}}><h3>มอบหมายขั้นตอนถัดไป</h3><label>เรื่องติดตาม<input value={reason} required maxLength={100} onChange={e=>setReason(e.target.value)}/></label><div className="form-grid"><label>ทีมรับผิดชอบ<input value={team} maxLength={100} onChange={e=>setTeam(e.target.value)}/></label><label>วันติดตามถัดไป<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><label>สถานะ<select value={status} onChange={e=>setStatus(e.target.value)}>{['open','in_progress','waiting','resolved'].map(x=><option key={x} value={x}>{statusNames[x]}</option>)}</select></label><label>หมายเหตุ<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><button className="button primary" disabled={busy}>บันทึกงานติดตาม <Check size={16}/></button></form>;
}
function EvidenceForm({id,busy,submit}:{id:number,busy:boolean,submit:(b:Row)=>void}){
 const [type,setType]=useState('SUBMISSION'),[amount,setAmount]=useState(''),[total,setTotal]=useState(''),[ref,setRef]=useState(''),[time,setTime]=useState(''),[reviewed,setReviewed]=useState(false),[component,setComponent]=useState('case_total');
 const requestId=useRef(crypto.randomUUID());
 return <details className="action-form"><summary>บันทึกหลักฐานส่ง / เงินรับ / กำหนดตามกฎ</summary><form onSubmit={e=>{e.preventDefault();submit({case_id:id,id:requestId.current,event_type:type,occurred_at:new Date(time).toISOString(),amount:amount||null,receipt_total:type==='CASH_RECEIPT'?total||null:null,source_ref:ref,component_key:component,verification:reviewed?'reviewed':'unverified'});}}><label>ประเภท<select value={type} onChange={e=>setType(e.target.value)}>{[['SUBMISSION','ส่งเบิกจริง'],['CASH_RECEIPT','เงินรับจริง'],['APPEAL_SENT','ส่งอุทธรณ์จริง'],['DEADLINE','กำหนดส่งที่ยืนยันแล้ว']].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div className="form-grid"><label>วันและเวลาตามหลักฐาน<input type="datetime-local" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>ยอดถึงเคสนี้ (บาท)<input inputMode="decimal" value={amount} required={type==='CASH_RECEIPT'} onChange={e=>setAmount(e.target.value)}/></label></div>{type==='CASH_RECEIPT'&&<label>ยอดรวมใบรับ / เงินโอน (บาท)<input inputMode="decimal" value={total} required onChange={e=>setTotal(e.target.value)}/></label>}<label>เลขที่ / ที่อ้างอิงหลักฐาน<input required minLength={3} value={ref} maxLength={500} onChange={e=>setRef(e.target.value)}/></label>{type==='SUBMISSION'&&<label>องค์ประกอบการส่ง (ใช้คีย์เดิมเมื่อส่งแก้ไข)<input required value={component} onChange={e=>setComponent(e.target.value)}/></label>}<label className="checkbox-label"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>ตรวจหลักฐานและความหมายยอดแล้ว</label><p className="muted">ใช้ UUID เดิมเมื่อ retry หลักฐานเดิม · เปลี่ยนเป็นรายการใหม่ด้วยการเปิดแฟ้มใหม่</p><button className="button secondary" disabled={busy}>บันทึกหลักฐาน</button></form></details>;
}
function AppealForm({id,claims,busy,submit}:{id:number,claims:Row[],busy:boolean,submit:(b:Row)=>void}){
 const options=claims.filter(c=>c.link_status==='linked'),[claim,setClaim]=useState(''),[reason,setReason]=useState('');const requestId=useRef(crypto.randomUUID());
 if(!options.length)return <p className="muted">ต้องมีเคลมที่จับคู่ชัดเจนก่อนเปิดอุทธรณ์</p>;
 return <form className="action-form" onSubmit={e=>{e.preventDefault();submit({case_id:id,claim_id:Number(claim||options[0].claim_id),reason,id:requestId.current});}}><label>เคลม<select value={claim||options[0].claim_id} onChange={e=>setClaim(e.target.value)}>{options.map(c=><option key={c.claim_id} value={c.claim_id}>{c.tran_id} · {c.payer_family}</option>)}</select></label><label>เหตุผล<textarea required minLength={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button secondary" disabled={busy}>เปิดอุทธรณ์พร้อมยอดฐาน</button></form>;
}
function AppealResultForm({id,busy,submit}:{id:string,busy:boolean,submit:(b:Row)=>void}){
 const [rows,setRows]=useState(''),[effect,setEffect]=useState('DELTA'),[outcome,setOutcome]=useState('approved'),[ref,setRef]=useState('');
 return <details className="action-form"><summary>ระบุผลพิจารณาจากหลักฐานใหม่</summary><form onSubmit={e=>{e.preventDefault();submit({statement_row_ids:rows.split(',').map(x=>Number(x.trim())),effect_type:effect,outcome,source_ref:ref});}}><label>Statement row IDs (คั่นด้วย comma)<input required pattern="[0-9, ]+" value={rows} onChange={e=>setRows(e.target.value)}/></label><label>ความหมายยอด<select value={effect} onChange={e=>setEffect(e.target.value)}><option value="DELTA">ยอดเพิ่ม / ลดโดยตรง</option><option value="REPLACEMENT">ยอดใหม่แทนฐานเดิม</option></select></label><label>ผล<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="approved">อนุมัติ</option><option value="partial">อนุมัติบางส่วน</option><option value="rejected">ไม่อนุมัติ</option></select></label><label>หลักฐานผล<input required minLength={3} value={ref} onChange={e=>setRef(e.target.value)}/></label><button className="button secondary" disabled={busy}>บันทึกผล · {id.slice(0,8)}</button></form></details>;
}

