import {useState,useEffect,useRef,type FormEvent} from 'react';
import {Activity,ArrowRight,BookOpen,Check,ChevronLeft,ChevronRight,ClipboardList,Clock,Database,FileCheck2,FileUp,FolderOpen,LayoutDashboard,LogOut,RefreshCw,Search,ShieldCheck,SlidersHorizontal,TriangleAlert,X} from 'lucide-react';
import {api,post,money,count,day,statusNames,message,type Row} from './api';
import {useApi,useVisiblePolling,currentFY,fyScope,scoped,Badge,Empty,Notice,Loading,Panel,type Scope} from './shared';
export function Imports({refresh,notify,demo}:{refresh:number,notify:(s:string)=>void,demo:boolean}){
 const [files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[job,setJob]=useState<string|null>(null),[poll,setPoll]=useState(0);const requestId=useRef(crypto.randomUUID());
 const jobs=useApi('/jobs',refresh+poll),detail=useApi(job?'/jobs/'+job:null,refresh+poll);
 useVisiblePolling(Boolean(jobs.data?.items?.some((j:Row)=>['queued','inspecting','importing','syncing','refreshing','verifying'].includes(j.status))),()=>setPoll(v=>v+1));
 const upload=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');const body=new FormData();files.forEach(f=>body.append('files',f));try{const result=await api('/imports/uploads',{method:'POST',body,headers:{'Idempotency-Key':requestId.current}});setJob(result.job_id);notify('รับไฟล์เข้าคิวตรวจแล้ว');requestId.current=crypto.randomUUID();setFiles([]);}catch(e){setError(message(e));}finally{setBusy(false);}};
 const action=async(id:string,verb:string)=>{try{await post(`/jobs/${id}/${verb}`);notify(verb==='start'?'เริ่มนำเข้าไฟล์ที่ผ่านตรวจ':'บันทึกคำสั่งงานแล้ว');setPoll(v=>v+1);}catch(e){setError(message(e));}};
 return <><Panel title="นำเข้าไฟล์ REP และ STM" caption="ตรวจรูปแบบและยอดก่อนนำเข้า · เก็บไฟล์ต้นฉบับและทุกฉบับแก้ไข"><form className="upload-zone" onSubmit={upload}><FileUp size={30}/><h3>เลือกไฟล์ .xls จากเครื่อง</h3><p>STM_10929_*.xls หรือ eclaim_10929_*.xls<br/>ไม่เกิน 20 ไฟล์ต่อครั้ง · 100 MiB ต่อไฟล์ · 300 MiB รวม</p><label className="file-picker">ไฟล์ที่ต้องการตรวจ<input type="file" accept=".xls" multiple disabled={demo||busy} onChange={e=>{setFiles(Array.from(e.target.files||[]));requestId.current=crypto.randomUUID();}}/></label>{files.length>0&&<ul className="selected-files">{files.map(f=><li key={f.name}>{f.name}<span>{(f.size/1024/1024).toFixed(2)} MiB</span></li>)}</ul>}<button className="button primary" disabled={demo||busy||!files.length}>{busy?'กำลังรับไฟล์…':'อัปโหลดและตรวจไฟล์'}<ArrowRight size={16}/></button>{demo&&<p className="muted">โหมดจำลองไม่รับไฟล์ผู้ป่วยจริง</p>}</form></Panel>{error&&<Notice tone="error">{error}</Notice>}
 <Panel title="ประวัติงานและ checkpoint" caption="เมื่อ timeout ใช้ resume ของงานเดิม เพื่อรักษา batch UUID"><div className="job-list">{jobs.loading?<Loading/>:jobs.error?<Notice tone="error">{jobs.error}</Notice>:!jobs.data?.items?.length?<Empty title="ยังไม่มีงาน">งานอัปโหลดและ HIS sync จะแสดงที่นี่</Empty>:jobs.data.items.map((j:Row)=><div className="job" key={j.id}><button className="job-title" onClick={()=>setJob(j.id)}><strong>{j.kind==='IMPORT'?'นำเข้า REP / STM':'อ่าน HIS'} · {j.id.slice(0,8)}</strong><small>{day(j.created_at)} · {count(j.progress?.records??j.progress?.inserted)} records</small></button><Badge value={j.status}/><div className="job-actions">{j.status==='awaiting_import'&&<button className="button primary" onClick={()=>action(j.id,'start')}>นำเข้าที่ผ่านตรวจ</button>}{['paused','failed','waiting_session'].includes(j.status)&&<button className="button secondary" onClick={()=>action(j.id,'resume')}>ทำต่อ</button>}{['queued','importing','syncing','inspecting'].includes(j.status)&&<button className="button secondary" onClick={()=>action(j.id,'pause')}>พักงาน</button>}</div>{j.error_code&&<small className="error-code">{j.error_code}</small>}</div>)}</div></Panel>
 {job&&<Panel title={'รายละเอียดงาน '+job.slice(0,8)} action={<button className="icon-button" aria-label="ปิดรายละเอียดงาน" onClick={()=>setJob(null)}><X size={18}/></button>}>{detail.loading?<Loading/>:detail.error?<Notice tone="error">{detail.error}</Notice>:<><pre className="operational-json">{JSON.stringify({progress:detail.data?.progress,result:detail.data?.result,error:detail.data?.error_code},null,2)}</pre>{detail.data?.files?.map((f:Row)=><details className="file-profile" key={f.id}><summary>{f.filename} · {statusNames[f.status]||f.status}</summary><p>SHA-256: <code>{f.sha256}</code></p><pre className="operational-json">{JSON.stringify(f.profile,null,2)}</pre></details>)}</>}</Panel>}</>;
}

export function His({refresh,notify,snapshots,onSnapshotRefresh,demo}:{refresh:number,notify:(s:string)=>void,snapshots:Row[],onSnapshotRefresh:()=>void,demo:boolean}){
 const [scope,setScope]=useState(fyScope(currentFY())),[busy,setBusy]=useState(false),[error,setError]=useState(''),[poll,setPoll]=useState(0);const requestId=useRef(crypto.randomUUID());const readiness=useApi('/readiness',refresh+poll),jobs=useApi('/jobs',refresh+poll);
 useVisiblePolling(Boolean(jobs.data?.items?.some((j:Row)=>j.kind==='HIS_SYNC'&&['queued','syncing','refreshing','verifying'].includes(j.status))),()=>{setPoll(v=>v+1);onSnapshotRefresh();});
 const sync=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const x=await post('/his/sync',{start:scope.start,end:scope.end,request_id:requestId.current});notify('เริ่มอ่าน HIS · '+x.job_id.slice(0,8));requestId.current=crypto.randomUUID();setPoll(v=>v+1);}catch(e){setError(message(e));}finally{setBusy(false);}};
 return <><Panel title="อ่าน HIS ผ่าน BMS Session" caption="อ่านเฉพาะ query registry · ไม่รับ SQL จาก browser"><form className="sync-form" onSubmit={sync}><div className="form-grid"><label>วันเริ่ม<input type="date" value={scope.start} max={scope.end} onChange={e=>setScope({...scope,start:e.target.value})}/></label><label>วันสิ้นสุด<input type="date" value={scope.end} min={scope.start} onChange={e=>setScope({...scope,end:e.target.value})}/></label></div><p>OPD ใช้วันบริการ · IPD ใช้วันจำหน่าย และเก็บผู้ป่วยที่ยังนอนแยกไว้ ไม่ลดตัวตั้งเมื่อยังไม่มีวินิจฉัย</p><button className="button primary" disabled={demo||busy}>เริ่มอ่านและสร้าง snapshot <ArrowRight size={16}/></button></form>{error&&<Notice tone="error">{error}</Notice>}<Notice>Session หมดอายุจะพักงานรอเชื่อมใหม่ ชุดข้อมูลที่อ่านไม่ครบระบุเป็น partial / unavailable และไม่แปลงยอดที่ขาดเป็นศูนย์</Notice></Panel><Panel title="สถานะแหล่งข้อมูล"><pre className="operational-json">{JSON.stringify(readiness.data,null,2)}</pre></Panel><Panel title="Snapshot และขอบเขตที่อ่านได้"><div className="snapshot-list">{snapshots.length?snapshots.map(s=><details key={s.id}><summary>{day(s.dstart)} – {day(s.dend)} <Badge value={s.status}/></summary><p>{s.id} · ณ {day(s.completed_at)}</p><pre className="operational-json">{JSON.stringify({coverage:s.coverage,registry:s.registry_profile,cost:s.cost_semantics},null,2)}</pre></details>):<Empty title="ยังไม่มี snapshot">เริ่มจากช่วงสั้นเพื่อตรวจสิทธิ API และต้นทุน ก่อนขยายช่วงย้อนหลัง</Empty>}</div></Panel></>;
}

export function Appeals({refresh,openCases}:{refresh:number,openCases:()=>void}){
 const {data,error,loading}=useApi('/appeals',refresh);
 return <Panel title="ประวัติอุทธรณ์และผลเพิ่มสุทธิ" caption="แยกจากการแก้ reject แล้วส่งใหม่" action={<button className="button secondary" onClick={openCases}>เปิดจากแฟ้มเคส <ArrowRight size={16}/></button>}>{error?<Notice tone="error">{error}</Notice>:loading?<Loading/>:!data?.items?.length?<Empty title="ยังไม่มีอุทธรณ์ที่บันทึก">เปิดแฟ้มเคส เลือกเคลม และตรึงฐานก่อนอุทธรณ์</Empty>:<div className="table-scroll"><table><thead><tr><th>แฟ้ม / เหตุผล</th><th>สถานะ</th><th className="num">ฐานเดิม</th><th className="num">เพิ่ม / ลดสุทธิ</th><th>หลักฐานผล</th></tr></thead><tbody>{data.items.map((a:Row)=><tr key={a.id}><td>{a.encounter_key}<small>{a.reason}</small></td><td>{a.status} · {a.outcome||'รอผล'}</td><td className="num">{money(a.baseline_amount)}</td><td className="num">{money(a.incremental_amount)}</td><td>{a.source_ref||'—'}</td></tr>)}</tbody></table></div>}</Panel>;
}
export function Quality({refresh,snapshot}:{refresh:number,snapshot:string}){
 const {data,error,loading}=useApi('/quality'+(snapshot?'?snapshot_id='+snapshot:''),refresh);
 return <><Notice>คอลัมน์ที่มีอยู่ใน schema ยังไม่ยืนยันว่ามีข้อมูลจริง ความหมายต้นทุน วันส่ง และ deadline ต้องผ่านการตรวจต้นทาง</Notice><Panel title="รายการตรวจ HIS"><IssueTable rows={data?.his||[]} loading={loading} error={error}/></Panel><Panel title="ข้อสังเกต REP / STM" caption="ปัญหา mapping ที่เป็น error พักเอกสารก่อนรวมยอด"><IssueTable rows={data?.rep_stm||[]} loading={loading}/></Panel></>;
}
function IssueTable({rows,loading,error}:{rows:Row[],loading:boolean,error?:string}){return error?<Notice tone="error">{error}</Notice>:loading?<Loading/>:!rows.length?<Empty title="ไม่มีปัญหาที่บันทึกในขอบเขตนี้">ยังต้องตรวจ coverage และความพร้อมของแต่ละแหล่ง</Empty>:<div className="table-scroll"><table><thead><tr><th>ระดับ</th><th>ประเด็น</th><th>ชุดข้อมูล / จำนวน</th><th>หลักฐาน</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><span className={'badge '+(r.severity==='error'?'bad':'review')}>{r.severity}</span></td><td>{r.code}</td><td>{r.dataset||count(r.count)}</td><td>{r.source_key||'—'}{r.detail&&<details><summary>รายละเอียด</summary><pre className="operational-json">{JSON.stringify(r.detail,null,2)}</pre></details>}</td></tr>)}</tbody></table></div>;}
export function Dictionary(){
 const {data,error,loading}=useApi('/dictionary'),[search,setSearch]=useState('');
 const tables=(data?.tables||[]).filter((t:Row)=>[t.name,t.meaning,...t.fields.map((f:Row)=>[f.name,f.meaning,f.source].join(' '))].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <Panel title="พจนานุกรมข้อมูลและที่มา" caption="คีย์จาก metadata แยกจากความสัมพันธ์ที่ยังต้องตรวจข้อมูลจริง"><label className="search-field dictionary-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นตาราง คอลัมน์ หรือความหมาย" aria-label="ค้น Data Dictionary"/></label>{loading?<Loading/>:error?<Notice tone="error">{error}</Notice>:tables.map((t:Row)=><details className="dictionary-table" key={t.name}><summary><code>{t.name}</code><span>{t.meaning}</span><small>{t.fields.length} ฟิลด์</small></summary><p>{t.grain} · {t.verification}</p><div className="table-scroll"><table><thead><tr><th>ฟิลด์ / ชนิด</th><th>ความหมาย / ที่มา</th><th>NULL / คีย์</th><th>ความเชื่อถือ / หน่วย</th></tr></thead><tbody>{t.fields.map((f:Row)=><tr key={f.name}><td><code>{f.name}</code><small>{f.type}</small></td><td>{f.meaning}<small>{f.source}</small></td><td>{f.nullable?'NULL ได้':'NOT NULL'} {f.key||''}</td><td>{f.verification}<small>{f.unit||'—'}</small></td></tr>)}</tbody></table></div></details>)}</Panel>;
}
export function Planning(){
 const [volume,setVolume]=useState('100'),[charge,setCharge]=useState(''),[cost,setCost]=useState(''),[recovery,setRecovery]=useState(''),[result,setResult]=useState<Row|null>(null),[error,setError]=useState('');const forecast=useApi('/planning/forecast');
 return <><Panel title="จำลองแผนบริการและการติดตาม" caption="เปลี่ยนสมมติฐานเพื่อดูผล · เป็นสถานการณ์ ไม่ใช่คำพยากรณ์"><form className="planning-form" onSubmit={async e=>{e.preventDefault();setError('');try{setResult(await post('/planning/scenario',{volume,charge_per_case:charge||null,cost_per_case:cost||null,verified_recovery_per_case:recovery||null}));}catch(e){setError(message(e));}}}><div className="form-grid"><label>จำนวนเคส<input type="number" min="0" step="1" required value={volume} onChange={e=>setVolume(e.target.value)}/></label><label>ค่าเรียกเก็บต่อเคส (บาท)<input inputMode="decimal" value={charge} onChange={e=>setCharge(e.target.value)}/></label><label>ต้นทุนรายการต่อเคส (บาท)<input inputMode="decimal" value={cost} onChange={e=>setCost(e.target.value)}/></label><label>โอกาสเรียกเก็บเพิ่มที่มีหลักฐานต่อเคส (บาท)<input inputMode="decimal" value={recovery} onChange={e=>setRecovery(e.target.value)}/></label></div><button className="button primary">คำนวณสถานการณ์ <ArrowRight size={16}/></button></form>{error&&<Notice tone="error">{error}</Notice>}{result&&<dl className="money-ledger">{[['ค่าเรียกเก็บตามสมมติฐาน',result.charge_amount],['ต้นทุนรายการตามสมมติฐาน',result.item_cost_amount],['โอกาสเรียกเก็บเพิ่ม',result.potential_recovery]].map(([label,v])=><div key={label}><dt>{label}</dt><dd>{money(v)} <span>บาท</span></dd></div>)}</dl>}</Panel><Panel title="การพยากรณ์จากประวัติ"><Notice>{forecast.data?.status==='NOT_READY'?'ยังไม่พร้อมพยากรณ์ ต้องมีประวัติครบอย่างน้อย 24 เดือนต่อเนื่องและนิยามตัวชี้วัดผ่านตรวจ':'แบบจำลองพื้นฐานที่ผ่าน backtest'}</Notice><p className="inline-caption">ประเมินย้อนหลังตามเวลา เทียบ seasonal naive และเดือนล่าสุด พร้อมรายงาน MAE และขอบเขตข้อมูลขาด</p></Panel></>;
}
